### ISSUE TITLE
회원가입시 form validation 이 제대로 되지 않네요

### ISSUE THREAD

**Issue by mia6111** [wwh-techcamp-2018/team5-fiveMasterGuys#120]
값을 입력하지 않거나 인풋이 잘못되었을때 
자바스크립트 에러가 뜨는것같아요! 

아래와 같이 에러 메세지가 출력되어요 
signup.js:1 Uncaught SyntaxError: Unexpected token {

utils.js:11 Uncaught TypeError: Cannot set property 'innerText' of undefined
    at validatePasswordValue (utils.js:11)
    at Signup.checkSignupForm (signup.js:62)
    at HTMLButtonElement.signupBtn.addEventListener (signup.js:26)
validatePasswordValue @ utils.js:11
checkSignupForm @ signup.js:62
signupBtn.addEventListener @ signup.js:26

**Comment by CHANMYUNG** [comment]
중복된 이슈라 close하겠습니다. 감사합니다 💯
