### ISSUE TITLE
[레시피] 스텝추가에서 제목과 내용을 길게 입력하고 +버튼을 누르면 길게 입력한 길이에 맞춰서 입력창 길이가 변경되요

### ISSUE THREAD

**Issue by DongHeeYun** [wwh-techcamp-2018/team5-fiveMasterGuys#122]
<img width="1299" alt="2018-08-24 5 19 25" src="https://user-images.githubusercontent.com/14209291/44573581-f70ab180-a7c1-11e8-8ec1-0b353f005dc2.png">

**Comment by CHANMYUNG** [comment]
딱걸렸네..
ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by CHANMYUNG** [comment]
감사합니다 👍
