### ISSUE TITLE
[메인페이지] 첫화면에 뜨는 포크 나이프 이미지 눌려있는것 같아요

### ISSUE THREAD

**Issue by jhyang12345** [wwh-techcamp-2018/team5-fiveMasterGuys#123]
소스 확인해보니까 눌려있는것 맞네요 고쳐주세요!

**Comment by CHANMYUNG** [comment]
아 4:3 비율로 맞춰져있어서 이미지가 눌리는 것처럼 보이는거 말씀하시는거죠? 감사합니다 👍

**Comment by CHANMYUNG** [comment]
#146 PR 머지커밋에 해당 사항 수정해 머지하였습니다.

https://github.com/wwh-techcamp-2018/team5-fiveMasterGuys/pull/146/commits/efcb51b0395fc433fcdfdf50a6272ccf4c44a434#diff-bb0c761ded741f5a11440e8d4f2bdcd3R15

감사합니다.
