### ISSUE TITLE
스탭 추가 제안하기 제목 입력길게 할시 저장이 안됨

### ISSUE THREAD

**Issue by songintae** [wwh-techcamp-2018/team5-fiveMasterGuys#126]
default 사이즈가 255인데 이것보다 좀 많이 길게 입력하고 추가하면 저장이 안되는거 같아요

**Comment by songintae** [comment]
<img width="1090" alt="2018-08-24 5 23 52" src="https://user-images.githubusercontent.com/19792798/44573847-b8292b80-a7c2-11e8-9d39-644152a0e69f.png">

**Comment by CHANMYUNG** [comment]
동일한 이슈가 이미 추가되어 close하겠습니다. 감사합니다 👍  💯
