### ISSUE TITLE
[레시피] 레시피에서 스탭추가할 때 문제

### ISSUE THREAD

**Issue by JunsuLime** [wwh-techcamp-2018/team5-fiveMasterGuys#128]
스텝이름

1. ㅁㅁ
2.
3. ㅁㅁㅁㅁㅁ

로 저장시

1, 2 만 저장이 되고 3은 누락되는 문제 발생

**Comment by CHANMYUNG** [comment]
입력하고 엔터를 눌러 확정시켜야 내용으로 인식합니다.
혹시 어떤 브라우저 사용중이세요? :)

**Comment by JunsuLime** [comment]
아 enter 를 넣지는 않고 그냥 + 버튼 눌러서 했어요!

브라우저는 chrome 입니당

**Comment by JunsuLime** [comment]
![image](https://user-images.githubusercontent.com/17852124/44574709-2111a300-a7c5-11e8-8efb-b61adddbd724.png)

**Comment by CHANMYUNG** [comment]
input 태그는 내용으로 인식되지 않기 때문에 엔터를 눌러서 확정지어줘야해요. ㅠㅠ UX피드백이네요. 감사합니다. 👍
