### ISSUE TITLE
회원가입이 안돼요

### ISSUE THREAD

**Issue by kimyeon0331** [wwh-techcamp-2018/team5-fiveMasterGuys#129]
<img width="773" alt="2018-08-24 5 26 59" src="https://user-images.githubusercontent.com/19780879/44573954-fde5f400-a7c2-11e8-9f82-9a275a225b1f.png">
이유를 모르겠는데 회원가가입이 안돼요! 이유를 알려주는 에러메세지 띄워주면 좋을 것 같아요

**Comment by Lahavas** [comment]
비밀번호 혹시 알려주실 수 있나요??

**Comment by CHANMYUNG** [comment]
현재 회원가입 실패 오류메시지를 띄워주는 코드에 문제가 있음을 확인했습니다.
이슈가 겹쳐서 닫을게요! 감사합니다!!
