### ISSUE TITLE
[테스트] Append하는 Step Offer에 대한 Acceptance Test 추가

### ISSUE THREAD

**Issue by Lahavas** [wwh-techcamp-2018/team5-fiveMasterGuys#140]

**Comment by ryuneeee** [comment]
https://github.com/wwh-techcamp-2018/team5-fiveMasterGuys/blob/develop/src/test/java/com/woowahan/techcamp/recipehub/step/controller/StepAcceptanceTest.java#L83

이거 여기에 있긴해요. 그때 같이 만들었어요 ㅋㅋㅋ
