### ISSUE TITLE
컨트리뷰터가 수정 요청을 하고 나면 수정 버튼이 보여서 그 스텝 수정 가능함

### ISSUE THREAD

**Issue by minzzzy** [wwh-techcamp-2018/team5-fiveMasterGuys#172]
<img width="532" alt="screen shot 2018-08-29 at 10 15 21 am" src="https://user-images.githubusercontent.com/22969551/44759336-84f4ec80-ab74-11e8-8aff-413ad93ff9ba.png">

**Comment by CHANMYUNG** [comment]
#180
