### ISSUE TITLE
이슈도 쓰고 프로젝트도 쓰고 있군요

### ISSUE THREAD

**Issue by crongro** [wwh-techcamp-2018/team5-fiveMasterGuys#55]
꼼꼼하게 우선순위까지 나열해둔건 좋네요.
깃을 잘 써서 무척좋습니다. 여러분들이 힘들지만 않다면 ㅎㅎ

issues 나 projects 의 관리(다 했으면 업뎃이트를 하거나 새로운 일을 올리는 등)시 
실제 현실과 sync해주는 게 쉽지 않아요.

이번주 회고를 거치면서 '너무 무리하고 있는거 아닌가!' 등 팀이 스스로 효율성을 진단하고 방법을 고민해보세요.

**Comment by CHANMYUNG** [comment]
파이팅!!!
