### ISSUE TITLE
[레시피] Step이 추가되면 추가된 이후의 step번호 증가(Front)

### ISSUE THREAD

**Issue by minzzzy** [wwh-techcamp-2018/team5-fiveMasterGuys#82]
- owner가 스텝을 생성하면 그 이후의 step들의 번호 증가
- user가 제안한 step이 approve되면 이후의 step들의 번호 증가

**Comment by ryuneeee** [comment]
Closed by https://github.com/wwh-techcamp-2018/team5-fiveMasterGuys/pull/105/files#diff-377d8e6fd72ca2065aa96178deb1d8a7R148
