### ISSUE TITLE
[공통] 이미지 업로드 최대/최소 사이즈 지정하기

### ISSUE THREAD

**Issue by CHANMYUNG** [wwh-techcamp-2018/team5-fiveMasterGuys#91]

**Comment by ffaass** [comment]
https://spring.io/guides/gs/uploading-files/

**Comment by CHANMYUNG** [comment]
이미지 압축 로직을 적용할 수 있다면 더 좋을듯

**Comment by CHANMYUNG** [comment]
생각해볼것
- 이미지 압축.
- 사이즈 제한을 어겼을 경우에 발생하는 Exception을 advice에서 캐치할 수 있을지.
